# Generated by Django 3.2.25 on 2026-03-02 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudBeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre(s)')),
                ('apellido_paterno', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(max_length=100, verbose_name='Apellido Materno')),
                ('curp', models.CharField(max_length=18, unique=True, verbose_name='CURP')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('nivel_estudio', models.CharField(choices=[('preparatoria', 'Preparatoria'), ('licenciatura', 'Licenciatura'), ('maestria', 'Maestría'), ('doctorado', 'Doctorado')], max_length=20, verbose_name='Nivel de Estudio')),
                ('institucion', models.CharField(max_length=200, verbose_name='Institución Educativa')),
                ('promedio', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Promedio')),
                ('semestre_actual', models.IntegerField(verbose_name='Semestre / Grado Actual')),
                ('ingreso_familiar_mensual', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ingreso Familiar Mensual ($)')),
                ('numero_dependientes', models.IntegerField(verbose_name='Número de Dependientes en el Hogar')),
                ('trabaja_actualmente', models.BooleanField(default=False, verbose_name='¿Trabaja actualmente?')),
                ('tipo_beca', models.CharField(choices=[('academica', 'Académica'), ('deportiva', 'Deportiva'), ('cultural', 'Cultural'), ('economica', 'Económica')], max_length=20, verbose_name='Tipo de Beca Solicitada')),
                ('motivo', models.TextField(verbose_name='Motivo de la Solicitud')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('puntaje', models.IntegerField(default=0, verbose_name='Puntaje Calculado')),
                ('observaciones_admin', models.TextField(blank=True, null=True, verbose_name='Observaciones del Administrador')),
            ],
            options={
                'verbose_name': 'Solicitud de Beca',
                'verbose_name_plural': 'Solicitudes de Becas',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
