# Generated by Django 6.0.2 on 2026-03-02 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('calificacion', models.FloatField(default=0)),
                ('ha_desertado', models.BooleanField(default=False)),
            ],
        ),
    ]
