# Generated by Django 5.2.11 on 2026-03-04 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='calificacion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='materia',
            name='estatus',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Cursando', 'Cursando'), ('Aprobada', 'Aprobada')], default='Pendiente', max_length=20),
        ),
    ]
