# Generated by Django 6.0.2 on 2026-03-02 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={'verbose_name': 'Alumno', 'verbose_name_plural': 'Alumnos'},
        ),
        migrations.AlterField(
            model_name='alumno',
            name='calificacion',
            field=models.FloatField(default=0, verbose_name='Calificación Actual'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='ha_desertado',
            field=models.BooleanField(default=False, verbose_name='¿Ha desertado?'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre Completo'),
        ),
    ]
