# Generated by Django 4.2.28 on 2026-03-02 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcion',
            name='fecha_inscripcion',
        ),
    ]
